### ISSUE TITLE
[BUG] 태그 등록 시, mistake 필드가 null이 되어 NPE 발생

### ISSUE THREAD

**Issue by gorapaduckoo** [coding-union-kr/siltarae-be#141]
## 버그 설명
- 태그를 등록할 때, 저장된 엔티티의 `getMistakes()`를 호출하면 null이 반환돼요.
```java
final Tag createdTag = Tag.builder()
                .name(tagCreateRequest.getName())
                .member(member)
                .build();

Tag tag = tagRepository.save(createdTag);
log.info("mistakes = {}", tag.getMistakes()); // null
```

## 정상 동작 시 예상 결과
null이 아니라 빈 리스트를 반환해야 해요.

## 스크린샷
<img width="1344" alt="스크린샷 2024-01-05 오후 2 52 57" src="https://github.com/coding-union-kr/siltarae-be/assets/67768976/b6b307dd-5e74-4fec-98b0-2e57e96e227e">

## 추가 설명
빌더 패턴을 사용한 게 문제이지 않을까 싶어요🤔

**Comment by woodowoon** [comment]
저번에 이야기가 나왔던 **@Builder.Default** 를 사용하실 예정이신가요?

**Comment by gorapaduckoo** [comment]
생성자에서 초기화를 해줄지, 아니면 `@Builder.Default`를 사용할지 고민중이에요.

**Comment by gorapaduckoo** [comment]
## 원인

### save() 메서드의 내부 동작
<img width="669" alt="SimpleJpaRepository.save()" src="https://github.com/coding-union-kr/siltarae-be/assets/67768976/20c9d972-46a2-43ab-be14-365c15ffd888">

<br>
<br>

JpaRepository의 구현체인 SimpleJpaRepository 클래스의 `save()` 메서드를 확인해 본 결과, `tagRepository.save()`가 반환하는 값은 영속성 컨텍스트에 영속된 객체였어요. 저희는 **`save()`를 호출하면 DB에 저장한 뒤, DB를 조회해서 DB에 저장된 값을 반환해준다고 생각했는데, 실제로는 저희가 저장하려고 만든 객체를 영속한 뒤에 그대로 반환**해준 거죠. (태그 등록 시 나가는 sql 쿼리는 확인 필요)

<br>
<br>

### 2. 빌더 패턴 사용 
<img width="416" alt="스크린샷 2024-01-05 오후 3 38 54" src="https://github.com/coding-union-kr/siltarae-be/assets/67768976/c2cdfc49-16b7-4130-ac7f-7f3bb7b9e81e">

<br>
<br>

저장할 태그(createdTag)를 생성할 때 mistakes 필드의 값을 지정해주지 않은 게 문제였어요. 저희는 **빌더 패턴을 이용해 객체를 생성했기 때문에, 지정되지 않은 mistakes 필드에는 빈 리스트 대신 null**이 들어갔고, 이 객체가 그대로 반환되면서 NPE가 발생했어요.

**Comment by woodowoon** [comment]
그래서 JpaRepository 에서 find 해왔던 객체에서는 NPE 가 발생하지않았는데 save 해서 반환된 객체에서는 NPE 가 발생했던 거군요 이해했습니다!  👍

**Comment by gorapaduckoo** [comment]
## 해결
```java
@Builder
    public Tag(Long id, String name, Member member, List<Mistake> mistakes) {
        this.id = id;
        this.name = name;
        this.member = member;
        this.mistakes = new ArrayList<>();
    }
```
태그 클래스의 생성자에서 빈 리스트로 초기화해주기로 결정했어요. `@Builder.Default`를 사용할 수도 있었지만, 이 어노테이션을 사용하기 위해서는 클래스 레벨에 `@Builder`어노테이션을 붙여야 했어요. 저희는 일괄적으로 생성자에 `@Builder` 어노테이션을 붙여 사용중이었기 때문에 코드 일관성을 위해 생성자 초기화를 선택했습니다.
