### ISSUE TITLE
[BUG] TagControllerTest에서 NullPointerException 발생

### ISSUE THREAD

**Issue by gorapaduckoo** [coding-union-kr/siltarae-be#59]
## 버그 설명
- 태그 엔티티에서 `tag.getMistake()` 메서드 호출 시 null이 반환됨

## 버그 발생 경위
- 아직 해당 태그에 속한 실수가 없는 상황
- `tag.getMistake().size()` 호출 시, `tag.getMistake()`의 값이 null이 되어 NullPointerException 발생

## 정상 동작 시 예상 결과
- null 대신 빈 리스트가 조회되어야 함

**Comment by woodowoon** [comment]
## 해결 방법
Domain Entity 의 해당하는 필드에 @Builder.Default 를 사용하여 null 일 경우 빈리스트를 반환하게끔 수정

**Comment by gorapaduckoo** [comment]
## 추가 설명
- 실제 컨트롤러 동작 시에는 빈 리스트 반환
- 컨트롤러 테스트에서는 `JPA metamodel must not be empty`라는 문구와 함께 BeanCreatingException 발생 
<img width="364" alt="스크린샷 2023-12-19 오후 5 11 34" src="https://github.com/coding-union-kr/siltarae-be/assets/67768976/519b51c3-233c-499a-a3f6-6311372c5f3d">

**Comment by gorapaduckoo** [comment]
## 원인
- Application 클래스에 `@EnableJpaAuditing` 어노테이션을 사용한 채, `@WebMvcTest`를 사용한 컨트롤러 테스트를 작성한 것이 문제였다. 
- `@WebMvcTest`는 웹 계층 관련 빈들만 로드한다. 따라서 `@Controller`, `@JsonComponent`가 붙은 빈들은 로드되지만, `@Component`, `@Service`, `@Repository`가 붙은 빈들은 로드되지 않는다. 하지만 SiltaraeBeApplication 클래스에 `@EnableJpaAuditing`을 붙임으로써, 매 테스트마다 로드되는 **Application 클래스가 JPA 관련 빈을 필요로 하게 되었다.**
- `@SpringBootTest`를 이용해 통합 테스트를 진행하는 경우, 전체 컨텍스트가 로드되기 때문에 JPA Auditing 관련 빈들도 함께 로드되어 문제가 발생하지 않는다. 하지만 여기서는 `@WebMvcTest`를 사용하여 단위 테스트를 진행했기 때문에, **JPA 관련 빈이 로드되지 않아 문제가 발생**하였다.

## 해결
**1. 설정 파일 분리**
JpaAuditing 관련 설정을 `JpaAuditingConfiguration` 클래스로 분리한다. 이렇게 하면 Application에 적용되던 `@EnableJpaAuditing`이 설정 클래스로 옮겨가고, 더 이상 Application 클래스가 JPA 관련 빈을 필요로 하지 않게 된다.
```java
@EnableJpaAuditing
@Configuration
public class JpaAuditingConfiguration {
    // ,,,
}
```

**2. 테스트 코드에 JPA 관련 MockBean 추가**
컨트롤러 테스트에 `@MockBean(JpaMetamodelMappingContext.class)` 어노테이션을 추가한다. 이렇게 하면 JPA Auditing과 관련된 빈들이 등록되어 단위 테스트가 정상적으로 수행된다.
```java
@MockBean(JpaMetamodelMappingContext.class)
@WebMvcTest(TagController.class)
class TagControllerTest {
    // ...
}
```

## 참고자료
[티스토리 - 나의 과거일지](https://jeongkyun-it.tistory.com/199)
[벨로그 - cjh8746.log](https://velog.io/@cjh8746/에러-JPA-metamodel-must-not-be-empty-해결기)

**Comment by gorapaduckoo** [comment]
@woodowoon 
해결 방법에 대한 매니님의 의견이 궁금합니다!

저는 아래와 같은 이유로 1번이 더 나을 것 같다고 생각하고 있어요!
- 설정이 많아지면, global.config 패키지에서 다양한 설정들을 한꺼번에 확인할 수 있어요.
- 단위 테스트 시 JPA Auditing 관련 MockBean을 로드할 필요가 없어져요. '필요한 빈들만 로드하는 것'이 단위 테스트의 의도에 좀 더 부합한다고 생각합니다!

**Comment by woodowoon** [comment]
저는 2번 방법으로도 정상 실행이 되질 않던데 정상 실행 되나요? 

- 2번 방법으로 정상실행이 되질 않았어서 저도 1번 방법이 더 좋습니다

**Comment by gorapaduckoo** [comment]
NullPointerException이 발생하는건 회사 태그와 일상 태그를 빌더 패턴으로 생성할 때, `mistakes` 값을 넣어주지 않아 해당 필드가 null이 되었기 때문이에요. 아래 코드처럼 빈 리스트를 넣어주면 정상적으로 동작하는걸 확인했습니다! 

```java
public static Tag COMPANY_TAG() {
    return Tag.builder()
            .id(1L)
            .name("회사")
            .mistakes(List.of())
            .build();
    }

public static Tag DAILY_TAG() {
    return Tag.builder()
            .id(1L)
            .name("일상")
            .mistakes(List.of())
            .build();
    }
```
